# Generated by Django 5.0.3 on 2024-04-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_user_options_remove_user_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.CharField(max_length=255, null=True, verbose_name='Estado'),
        ),
    ]
