# Generated by Django 5.0.3 on 2024-04-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_address_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address',
        ),
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=255, null=True, verbose_name='Rua'),
        ),
    ]
