# Generated by Django 5.0.3 on 2024-03-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='base',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
