# Generated by Django 5.0.3 on 2024-04-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_category_options_alter_picture_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
